name: dart_microservice
description: A sample command-line application with database integration.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mysql1: 0.20.0       # For MySQL and MariaDB
  mongo_dart: 0.10.3   # For MongoDB
  http: 1.2.2
  postgres: ^2.3.1
  shelf: ^1.3.0
  shelf_router: ^1.0.0

dev_dependencies:
  lints: 4.0.0
  test: 1.25.8
