name: dart_microservice
description: A sample command-line application with database integration.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Database dependencies
  mysql1: ^0.20.2       # For MySQL and MariaDB
  mongo_dart: ^0.8.3    # For MongoDB
  http: ^0.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
